apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  PRODUCT_API_URL: "http://product-api-service:5000"
  ORDER_API_URL: "http://order-api-service:8080"
  API_TIMEOUT: "30000"
  ENABLE_METRICS: "true"
