apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: techcommerce
  labels:
    app: order-api
spec:
  type: ClusterIP
  selector:
    app: order-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None
