apiVersion: v1
kind: Secret
metadata:
  name: product-api-secret
  namespace: techcommerce
type: Opaque
stringData:
  DB_USERNAME: "product_user"
  DB_PASSWORD: "P@ssw0rd!2024_Change_Me"
  SECRET_KEY: "your-super-secret-flask-key-change-this"
  JWT_SECRET: "jwt-secret-key-change-in-production"
  REDIS_PASSWORD: "redis_secure_password_2024"
  API_KEY: "external-api-key-12345"
