apiVersion: v1
kind: Service
metadata:
  name: product-api-service
  namespace: techcommerce
  labels:
    app: product-api
spec:
  type: ClusterIP
  selector:
    app: product-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  sessionAffinity: None
